#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

if [ $# -ne 2 ]; then
    echo "Usage: $(basename $0) video.mp4 outdir"
    exit 1
fi

ffmpeg -y -loglevel error -skip_frame nokey -i "${1}" -vsync 0 -f image2 "${2}/frame-%d.jpg"
